Repository openai/openai-agents-python, pull requests merged in 2025-08, with the labels that each got.

#1330 docs: Clarify and enhance run_demo_loop utility documentation for beginners
  docs/repl.md
Labels: documentation

#1339 Fix set_api_key breaking cached property mechanism
  src/agents/tracing/processors.py
  tests/tracing/test_set_api_key_fix.py
Labels: bug, feature:tracing

#974 Feat: separate tool_call_item and tool_call_output_item in stream events
  src/agents/_run_impl.py
  src/agents/run.py
  tests/test_stream_events.py
  uv.lock
Labels: bug, enhancement, feature:core

#1296 Clarify shallow-copy behavior of tools and handoffs in Agent.clone()
  src/agents/agent.py
  tests/test_agent_clone_shallow_copy.py
Labels: documentation, feature:core

#1278 Fix #1277 missing StopAtTools and ToolsToFinalOutputFunction in agents module
  src/agents/__init__.py
Labels: bug, documentation, feature:core

#1356 Fix style and wording issues in handoffs.py
  src/agents/handoffs.py
Labels: documentation, feature:core

#1360 Fix docstring formatting and add safe check for empty message content
  src/agents/items.py
Labels: documentation, feature:core

#1368 feat(viz): draw MCP servers
  docs/visualization.md
  src/agents/extensions/visualization.py
  tests/test_visualization.py
Labels: enhancement, feature:mcp, feature:visualizations

#1388 Realtime: send session update before tool response
  src/agents/realtime/session.py
Labels: feature:sessions

#1398 v0.2.5
  pyproject.toml
  uv.lock
Labels: project

#1063 Enhanced FAQ lookup tool in examples/customer_service app
  examples/customer_service/main.py
Labels: documentation

#1386 Improve accuracy of guardrails and lifecycle hook descriptions
  docs/index.md
  src/agents/lifecycle.py
Labels: documentation, feature:core

#971 Add logprobs to ModelSettings
  src/agents/extensions/models/litellm_model.py
  src/agents/model_settings.py
  src/agents/models/openai_chatcompletions.py
  src/agents/models/openai_responses.py
  tests/model_settings/test_serialization.py
  tests/test_logprobs.py
Labels: enhancement, feature:core, feature:chat-completions, feature:lite-llm

#1392 Updated the default values for two parameters in the ModelSettings class to align with their documented behavior:
  src/agents/model_settings.py
Labels: documentation

#998 Added runtime validation for Agent constructor arguments
  src/agents/agent.py
  tests/test_agent_config.py
Labels: enhancement, feature:core

#1399 feat(tests): add tests for unicode content, special characters, and concurrent access in SQLiteSession
  tests/test_session.py
Labels: feature:sessions

#1439 Fix #1407 Add reasoning.effort="minimal" and "verbosity" params to ModelSettings
  examples/basic/simple_gpt_5.py
  src/agents/model_settings.py
  src/agents/models/openai_chatcompletions.py
  src/agents/models/openai_responses.py
  tests/model_settings/test_serialization.py
Labels: enhancement, feature:core, feature:chat-completions

#1440 Add a simple gpt-oss example
  examples/basic/hello_world_gpt_oss.py
Labels: documentation, feature:chat-completions

#1461 Fix: Clarify random_number function docstring for inclusive range
  examples/basic/agent_lifecycle_example.py
Labels: documentation

#1472 docs: Clarify the `is_enabled` parameter in `handoff()` documentation
  docs/handoffs.md
Labels: documentation

#1475 Fix: Clarify random_number function docstring for inclusive range
  examples/basic/lifecycle_example.py
Labels: documentation

#1476 Add input validation and type conversion for user input
  examples/basic/lifecycle_example.py
Labels: documentation

#1478 Docs: Add missing docstring to get_weather function
  examples/basic/tools.py
Labels: documentation

#1482 Docs: Clarify that guardrails apply to both user input and agent output
  docs/agents.md
Labels: documentation

#1479 Docs: Add missing docstring to how_many_jokes tool
  examples/basic/stream_items.py
Labels: documentation

#1483 Allow modifying the input sent to the model
  src/agents/run.py
  tests/test_call_model_input_filter.py
  tests/test_call_model_input_filter_unit.py
Labels: enhancement, feature:core

#1502 Fix #1494 by adding a link to Responses API documentation
  src/agents/model_settings.py
Labels: documentation

#1193 Add conditional tool enabling feature to agent as tool.
  docs/tools.md
  examples/agent_patterns/agents_as_tools_conditional.py
  src/agents/agent.py
  tests/test_agent_as_tool.py
Labels: enhancement, feature:core, skip-stale

#1518 Add documentation for token usage tracking
  docs/usage.md
  examples/basic/usage_tracking.py
  mkdocs.yml
Labels: documentation

#1554 feat: add retry logic to MCP server operations
  src/agents/mcp/server.py
  tests/mcp/test_client_session_retries.py
Labels: codex

#1552 Realtime: input timeout trigger event
  examples/realtime/app/server.py
  src/agents/realtime/config.py
  src/agents/realtime/events.py
  src/agents/realtime/model_events.py
  src/agents/realtime/openai_realtime.py
  src/agents/realtime/session.py
Labels: feature:realtime

#1534 Add a quick opt-in option to switch to gpt-5 model
  examples/financial_research_agent/agents/search_agent.py
  examples/handoffs/message_filter.py
  examples/handoffs/message_filter_streaming.py
  examples/hosted_mcp/approvals.py
  examples/hosted_mcp/simple.py
  examples/reasoning_content/main.py
  examples/reasoning_content/runner_example.py
  examples/research_bot/agents/planner_agent.py
  examples/research_bot/agents/search_agent.py
  examples/research_bot/agents/writer_agent.py
  examples/tools/code_interpreter.py
  examples/tools/file_search.py
  examples/voice/static/main.py
  src/agents/agent.py
  src/agents/extensions/models/litellm_provider.py
  src/agents/models/__init__.py
  src/agents/models/default_models.py
  src/agents/models/openai_provider.py
  tests/models/test_default_models.py
Labels: enhancement, feature:core, feature:lite-llm

#1601 Fix #1592 Web search tool updates
  examples/tools/web_search_filters.py
  src/agents/model_settings.py
  src/agents/models/openai_responses.py
  src/agents/tool.py
  tests/test_openai_responses_converter.py
Labels: enhancement, feature:core

#1602 Handle LiteLLM's json_tool_call addition for structured outputs
  examples/model_providers/litellm_auto.py
  src/agents/_run_impl.py
Labels: enhancement, feature:lite-llm

#1586 Add reasoning text delta event support for gpt-oss models
  examples/reasoning_content/gpt_oss_stream.py
  src/agents/models/chatcmpl_stream_handler.py
Labels: enhancement, feature:core, feature:chat-completions

#1587 Fix #1564 Add conversations API support
  examples/memory/openai_session_example.py
  examples/memory/sqlalchemy_session_example.py
  examples/memory/sqlite_session_example.py
  examples/reasoning_content/main.py
  src/agents/__init__.py
  src/agents/extensions/models/litellm_model.py
  src/agents/memory/__init__.py
  src/agents/memory/openai_conversations_session.py
  src/agents/memory/session.py
  src/agents/memory/sqlite_session.py
  src/agents/models/interface.py
  src/agents/models/openai_chatcompletions.py
  src/agents/models/openai_responses.py
  src/agents/run.py
  tests/fake_model.py
  tests/models/test_kwargs_functionality.py
  tests/models/test_litellm_chatcompletions_stream.py
  tests/test_agent_prompt.py
  tests/test_extra_headers.py
  tests/test_openai_chatcompletions.py
  tests/test_openai_chatcompletions_stream.py
  tests/test_reasoning_content.py
  tests/test_responses_tracing.py
  tests/voice/test_workflow.py
Labels: enhancement, feature:core
