Repository openai/openai-agents-python, pull requests merged in 2025-09, with the labels that each got.

#1626 docs: Fix #1625 code snippet error
  docs/agents.md
Labels: documentation

#1624 fixed_typo: wiht -> with
  docs/realtime/guide.md
Labels: documentation

#1619 fix(run): fire on_llm_start / on_llm_end in Runner.run() for streaming & non-streaming (aligns with docs)
  examples/basic/lifecycle_example.py
  src/agents/run.py
  tests/test_run_hooks.py
Labels: bug, feature:core

#1637 Docs: Fix confusing session usage docs
  docs/usage.md
Labels: documentation

#1641 fix: Fix #1640 openai package breaking changes
  examples/tools/web_search_filters.py
  pyproject.toml
  src/agents/models/openai_responses.py
  src/agents/tool.py
  uv.lock
Labels: bug, feature:core

#1647 Improve translation prompt guidance
  docs/scripts/translate_docs.py
Labels: documentation, codex, project

#1657 Use head commit in docs workflow PR body
  .github/workflows/update-docs.yml
Labels: documentation, codex, project

#1665 Code snippet error in "Running Agents" document
  docs/running_agents.md
Labels: documentation

#1537 fix(voice/stt): accept conversation.item.input_audio_transcription.completed (keep legacy alias)
  src/agents/voice/models/openai_stt.py
  tests/voice/test_openai_stt.py
Labels: enhancement, feature:voice

#1688 Fix instructions not being applied
  src/agents/realtime/session.py
Labels: bug, feature:realtime

#1682 Fix a bug where the default behavior of loading the debug flag differs from the documentation
  src/agents/_debug.py
  tests/test_debug.py
Labels: bug, feature:core

#1684 fix: #1661 Preserve realtime session voice settings when updating agents
  src/agents/realtime/session.py
  tests/realtime/test_session.py
Labels: bug, codex, feature:realtime

#1689 Prevent preamble messages from being treated as final output when tool calls are pending
  src/agents/_run_impl.py
  tests/test_agent_runner.py
  tests/test_agent_runner_streamed.py
Labels: bug, feature:core

#1700 Fix session history duplication after PR #1550
  src/agents/run.py
Labels: bug, feature:sessions

#1710 Fix CI failure in `make old_version_tests`
  .github/workflows/tests.yml
Labels: project

#1739 docs: add docstring for parameter session in run, run_sync and run_streamed functions
  src/agents/run.py
Labels: documentation, feature:core

#1745 Fixed Race Condition in RunResultStreaming.stream_events() Method
  src/agents/result.py
Labels: bug, feature:core

#1749 feat(realtime): #1560 add input audio noise reduction
  docs/ref/realtime/config.md
  src/agents/realtime/__init__.py
  src/agents/realtime/config.py
  src/agents/realtime/openai_realtime.py
  tests/realtime/test_openai_realtime.py
Labels: enhancement, feature:realtime

#1759 feat(voice)!: migrate STT streaming to match GA Realtime API
  src/agents/tracing/spans.py
  src/agents/voice/models/openai_stt.py
  tests/voice/test_openai_stt.py
Labels: bug, feature:voice

#1740 docs: reformat run module docstrings to Google style for better mkdocstrings rendering
  src/agents/run.py
Labels: documentation

#1757 fixl: #1668 Handoffs with gpt-5* model + store=False + remove_all_tools fails due to 404 error response
  src/agents/extensions/handoff_filters.py
  tests/test_extension_filters.py
Labels: bug, feature:core

#1758 Add warning for agent names that transform into conflicting function names
  src/agents/util/_transforms.py
Labels: feature:core

#1768 Export `user_agent_override` contextmanager
  src/agents/extensions/models/litellm_model.py
  src/agents/models/chatcmpl_helpers.py
  src/agents/models/openai_chatcompletions.py
  src/agents/models/openai_responses.py
  tests/models/test_litellm_user_agent.py
  tests/test_openai_chatcompletions.py
  tests/test_openai_responses.py
Labels: enhancement, feature:core, feature:lite-llm

#1752 fix #1750 better error message when passing AgentHooks to Runner
  src/agents/run.py
  tests/test_run_hooks.py
Labels: enhancement, feature:core

#1777 Enhance function tool schemas with Annotated types
  examples/basic/stream_function_call_args.py
Labels: documentation

#1784 fix(chatcmpl): preserve text content when adding Anthropic thinking blocks to tool calls
  src/agents/models/chatcmpl_converter.py
  tests/test_anthropic_thinking_blocks.py
Labels: feature:chat-completions, feature:lite-llm

#1782 fix: #556 add llms.txt / llms-full.txt
  docs/llms-full.txt
  docs/llms.txt
Labels: documentation

#1765 Add tool call arguments in ToolContext for RunHooks
  examples/basic/lifecycle_example.py
  src/agents/realtime/session.py
  src/agents/tool_context.py
  tests/test_agent_as_tool.py
  tests/test_function_tool.py
  tests/test_function_tool_decorator.py
Labels: enhancement, feature:core

#1798 Fix extended thinking bug by reordering tool messages
  src/agents/extensions/models/litellm_model.py
  src/agents/models/chatcmpl_converter.py
  tests/test_extended_thinking_message_order.py
Labels: enhancement, feature:chat-completions, feature:lite-llm

#1809 Add agent hooks to lifecycle_example
  examples/basic/lifecycle_example.py
Labels: documentation, feature:core

#1810 Update models in docs
  docs/agents.md
  docs/voice/quickstart.md
  examples/voice/streamed/my_workflow.py
Labels: documentation

#1792 Adding tool input and output guardrails
  docs/guardrails.md
  examples/basic/tool_guardrails.py
  src/agents/__init__.py
  src/agents/_run_impl.py
  src/agents/exceptions.py
  src/agents/result.py
  src/agents/run.py
  src/agents/tool.py
  src/agents/tool_guardrails.py
  tests/extensions/memory/test_advanced_sqlite_session.py
  tests/test_result_cast.py
  tests/test_tool_guardrails.py
Labels: enhancement, feature:core

#1816 Korean translation
  docs/scripts/translate_docs.py
  mkdocs.yml
Labels: documentation

#1819 docs: update examples.md to match current examples directory structure
  docs/examples.md
Labels: documentation

#1825 Add missing parens in docs links
  docs/ja/tracing.md
  docs/ko/tracing.md
  docs/tracing.md
Labels: documentation
