Repository openai/openai-agents-python, pull requests merged in 2025-06, with the labels that each got.

#799 Fix #777 by handling MCPCall events in RunImpl
  examples/hosted_mcp/approvals.py
  examples/hosted_mcp/simple.py
  src/agents/_run_impl.py
Labels: bug

#811 Add REPL run_demo_loop helper
  docs/ja/repl.md
  docs/ref/repl.md
  docs/repl.md
  mkdocs.yml
  src/agents/__init__.py
  src/agents/repl.py
  tests/test_repl.py
Labels: codex

#814 Add release documentation
  docs/release.md
  mkdocs.yml
Labels: codex

#818 Fix handoff transfer message JSON
  src/agents/handoffs.py
  tests/test_handoff_tool.py
Labels: codex

#886 Introduce AgentRunner class
  src/agents/__init__.py
  src/agents/run.py
  tests/conftest.py
  tests/test_run.py
Labels: codex

#936 Add exempt-issue-labels to the issue triage GH Action job
  .github/workflows/issues.yml
Labels: enhancement

#897 Remove duplicate entry from `__init__.py`
  src/agents/__init__.py
Labels: bug, documentation, feature:core

#935 Fix #604 Chat Completion model raises runtime error when response.choices is empty
  src/agents/models/openai_chatcompletions.py
Labels: bug, feature:chat-completions

#937 Fix #892 by adding proper tool description in context.md
  docs/context.md
Labels: documentation

#951 Duplicate Classifier in pyproject.toml
  pyproject.toml
Labels: documentation

#639 fix: add ensure_ascii=False to json.dumps for correct Unicode output
  src/agents/extensions/models/litellm_model.py
  src/agents/models/openai_chatcompletions.py
  src/agents/models/openai_responses.py
Labels: enhancement, feature:core, feature:chat-completions, feature:lite-llm

#909 Add uv as an alternative Python environment setup option for issue #884
  README.md
Labels: documentation

#763 Fix and Document `parallel_tool_calls` Attribute in ModelSettings
  src/agents/model_settings.py
Labels: documentation, feature:core

#262 replace .py file with .ipynb for Jupyter example
  README.md
  examples/basic/hello_world_jupyter.ipynb
  examples/basic/hello_world_jupyter.py
Labels: documentation

#861 feat: add MCP tool filtering support
  docs/ja/mcp.md
  docs/mcp.md
  src/agents/agent.py
  src/agents/mcp/__init__.py
  src/agents/mcp/server.py
  src/agents/mcp/util.py
  src/agents/tool.py
  tests/mcp/helpers.py
  tests/mcp/test_caching.py
  tests/mcp/test_mcp_util.py
  tests/mcp/test_server_errors.py
  tests/mcp/test_tool_filtering.py
Labels: enhancement, feature:mcp

#958 Fix incorrect argument description in `on_trace_end` docstring
  src/agents/tracing/processor_interface.py
Labels: documentation

#923 Add safety check handling for ComputerTool
  src/agents/_run_impl.py
  src/agents/tool.py
  tests/test_computer_action.py
Labels: enhancement, codex, feature:core
