Repository openai/openai-agents-python, pull requests merged in 2025-07, with the labels that each got.

#1015 Fix agent lifecycle example output to reflect correct hook execution order
  examples/basic/agent_lifecycle_example.py
  examples/basic/lifecycle_example.py
Labels: documentation

#1000 description_override is not properly used for function_schema.description
  src/agents/function_schema.py
Labels: bug, feature:core

#990 avoid concat tool call delta id
  src/agents/models/chatcmpl_stream_handler.py
Labels: bug, feature:core

#1055 Updated llm_as_a_judge.py
  examples/agent_patterns/llm_as_a_judge.py
Labels: documentation

#1076 [8/n] Make realtime more like the rest of agents sdk
  .vscode/launch.json
  examples/realtime/demo.py
  src/agents/realtime/__init__.py
  src/agents/realtime/config.py
  src/agents/realtime/events.py
  src/agents/realtime/model.py
  src/agents/realtime/model_events.py
  src/agents/realtime/openai_realtime.py
  src/agents/realtime/runner.py
  src/agents/realtime/session.py
  src/agents/realtime/transport.py
  tests/realtime/test_model_events.py
Labels: enhancement, feature:realtime

#1080 Tests for realtime session
  src/agents/realtime/session.py
  tests/realtime/test_session.py
Labels: feature:realtime

#1034 Fix #968 by upgrading openai package to the latest
  pyproject.toml
  src/agents/model_settings.py
  src/agents/models/chatcmpl_converter.py
  src/agents/models/openai_responses.py
  tests/model_settings/test_serialization.py
  tests/test_items_helpers.py
  tests/test_run_step_processing.py
  uv.lock
Labels: bug, feature:core

#1084 Realtime tracing
  src/agents/realtime/config.py
  src/agents/realtime/model.py
  src/agents/realtime/openai_realtime.py
  src/agents/realtime/runner.py
  tests/realtime/test_tracing.py
Labels: feature:realtime

#1086 Fix incorrect comment order when popping session items
  docs/sessions.md
Labels: documentation, feature:session

#1122 Fix typos and update async for loop variable
  src/agents/agent.py
  src/agents/tool.py
  tests/test_session_exceptions.py
Labels: documentation, feature:core

#1113 Update examples docs with realtime section
  docs/examples.md
Labels: documentation, codex, feature:realtime

#1110 Retry: Add tool_name to ToolContext for generic tool handlers
  docs/tools.md
  mkdocs.yml
  src/agents/_run_impl.py
  src/agents/realtime/session.py
  src/agents/tool_context.py
  tests/test_function_tool.py
  tests/test_function_tool_decorator.py
Labels: enhancement, feature:core, feature:realtime

#1119 Realtime: fix item parsing
  examples/realtime/demo.py
  src/agents/realtime/__init__.py
  src/agents/realtime/items.py
  src/agents/realtime/openai_realtime.py
  tests/realtime/test_item_parsing.py
  tests/realtime/test_session.py
Labels: feature:realtime

#1120 v0.2.0
  docs/release.md
  pyproject.toml
  uv.lock
Labels: project

#1139 Realtime: handoffs
  src/agents/agent.py
  src/agents/guardrail.py
  src/agents/handoffs.py
  src/agents/models/chatcmpl_converter.py
  src/agents/models/openai_responses.py
  src/agents/realtime/__init__.py
  src/agents/realtime/agent.py
  src/agents/realtime/config.py
  src/agents/realtime/handoffs.py
  src/agents/realtime/openai_realtime.py
  src/agents/realtime/session.py
  tests/realtime/test_realtime_handoffs.py
  tests/realtime/test_session.py
  tests/test_handoff_tool.py
Labels: enhancement, feature:realtime

#1162 Adjust #598 to only create a PR rather than pushing changes to main branch
  .github/workflows/update-docs.yml
Labels: documentation, codex

#1181 fix: ensure ResponseUsage token fields are int, not None (fixes #1179)
  src/agents/models/chatcmpl_stream_handler.py
Labels: bug, feature:chat-completions

#1161 Add missing guardrail exception import to quickstart
  docs/quickstart.md
Labels: documentation

#1131 Mark some dataclasses as pydantic dataclasses
  src/agents/items.py
  src/agents/model_settings.py
  src/agents/usage.py
Labels: enhancement, feature:core

#1041 fix: Apply strict JSON schema validation in FunctionTool constructor
  src/agents/tool.py
Labels: enhancement, feature:core

#1180 Fix image_generator example error on Windows OS
  examples/tools/image_generator.py
Labels: documentation

#1048 Add automation script to generate mkdocstrings files
  Makefile
  docs/ref/computer.md
  docs/ref/extensions/models/litellm_model.md
  docs/ref/extensions/models/litellm_provider.md
  docs/ref/extensions/visualization.md
  docs/ref/logger.md
  docs/ref/models/chatcmpl_converter.md
  docs/ref/models/chatcmpl_helpers.md
  docs/ref/models/chatcmpl_stream_handler.md
  docs/ref/models/fake_id.md
  docs/ref/models/multi_provider.md
  docs/ref/models/openai_provider.md
  docs/ref/prompts.md
  docs/ref/strict_schema.md
  docs/ref/tool_context.md
  docs/ref/tracing/logger.md
  docs/ref/tracing/provider.md
  docs/ref/version.md
  docs/ref/voice/imports.md
  docs/ref/voice/models/openai_model_provider.md
  docs/scripts/generate_ref_files.py
  mkdocs.yml
Labels: documentation

#1203 Add prototype structure for banking demo
  .env.example
  backend/.gitignore
  backend/README.md
  backend/__init__.py
  backend/main.py
  backend/pyproject.toml
  backend/tests/test_main.py
  docs/banking-demo.md
  frontend/.gitignore
  frontend/README.md
  frontend/next.config.js
  frontend/package.json
  frontend/pages/index.tsx
  frontend/public/.gitkeep
  frontend/tests/example.test.ts
  frontend/tsconfig.json
  start.sh
Labels: codex

#1212 Fixes two issues in the tracing documentation
  docs/tracing.md
Labels: documentation

#1240 Add LiteLLM to acknowledgements section
  README.md
Labels: documentation

#1241 [Bugfix] Fix wrong imports in examples
  examples/reasoning_content/main.py
Labels: bug, documentation

#1235 Realtime: send audio item/content index
  src/agents/realtime/events.py
  src/agents/realtime/model_events.py
  src/agents/realtime/openai_realtime.py
  src/agents/realtime/session.py
  tests/realtime/test_session.py
Labels: enhancement, feature:realtime

#1246 Fix #1227 Chat Completions model fails to handle streaming with openai 1.97.1+
  pyproject.toml
  src/agents/models/chatcmpl_stream_handler.py
  tests/voice/test_workflow.py
  uv.lock
Labels: bug, feature:chat-completions

#1224 docs: add LangDB AI Gateway as a tracing provider
  docs/tracing.md
Labels: documentation

#1259 Fix type placeholder convention
  src/agents/agent_output.py
Labels: documentation, feature:core

#1260 Tweak on guardrail docstrings
  src/agents/guardrail.py
Labels: documentation, feature:core

#1266 gpt 4.5-preview is removed, use gpt-4.1
  examples/financial_research_agent/agents/writer_agent.py
Labels: documentation

#1268 Fix etc. punctuation
  src/agents/agent.py
Labels: documentation

#1272 Fix documentation typo and trailing comma in exporters
  src/agents/tracing/processors.py
Labels: documentation, feature:tracing

#1273 docs: remove non existent even_if_trace_running mention from trace docstring
  src/agents/tracing/create.py
Labels: documentation, feature:tracing

#1098 fix: convert litellm response with reasoning content to openai message
  src/agents/extensions/models/litellm_model.py
  src/agents/models/chatcmpl_converter.py
Labels: feature:chat-completions, feature:lite-llm

#1280 docs: fix UserContext example
  docs/agents.md
  docs/ja/agents.md
  docs/scripts/generate_ref_files.py
Labels: documentation

#1287 Fix _export_batches docstring to remove incorrect "threshold" reference
  src/agents/tracing/processors.py
Labels: documentation, feature:tracing

#1286 Enhance Tool Behavior Documentation for Developer Clarity With Examples
  docs/agents.md
Labels: documentation

#1242 Realtime: enable a playback tracker
  src/agents/realtime/__init__.py
  src/agents/realtime/_default_tracker.py
  src/agents/realtime/_util.py
  src/agents/realtime/model.py
  src/agents/realtime/openai_realtime.py
  tests/realtime/test_agent.py
  tests/realtime/test_conversion_helpers.py
  tests/realtime/test_openai_realtime.py
  tests/realtime/test_playback_tracker.py
Labels: feature:realtime

#1307 Fix tag errors in sessions document page
  docs/sessions.md
Labels: documentation

#1302 Fix #1238 by enhancing HandoffInputData and enable passing async functions
  examples/handoffs/message_filter.py
  examples/handoffs/message_filter_streaming.py
  src/agents/_run_impl.py
  src/agents/extensions/handoff_filters.py
  src/agents/handoffs.py
  tests/test_agent_runner.py
  tests/test_agent_runner_streamed.py
  tests/test_extension_filters.py
  tests/test_handoff_tool.py
Labels: enhancement, feature:core

#1309 Add support to realtime API for setting "speed" of the models responses
  src/agents/realtime/config.py
  src/agents/realtime/openai_realtime.py
Labels: enhancement, feature:realtime

#1319 Examples: use agent to interact with Remote PDF Documents
  examples/basic/remote_pdf.py
Labels: documentation
